# Generated by Django 2.0.4 on 2018-05-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traspasos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='cantidad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='codigo',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='codigobarra',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='local_destino',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='local_origen',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='numero_vale',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='preciocompra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='precioventa',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traspasos_entre_locales',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Tipo2'),
        ),
    ]
