# Generated by Django 2.0.4 on 2018-05-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('barra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eliminados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('local', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('local', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('stock_computador', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('fecha_inventario', models.DateTimeField()),
                ('diferencia_inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('laboratorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listado_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_barra', models.IntegerField()),
                ('preciocompra', models.FloatField()),
                ('fechacreacion', models.DateField()),
                ('laboratorio', models.IntegerField()),
                ('precioventa', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('factor', models.FloatField()),
                ('pedido', models.IntegerField()),
                ('ultimo_proveedor', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fecha_ultima_compra', models.DateField()),
                ('faltas', models.BooleanField()),
                ('tipo', models.IntegerField()),
                ('eliminado', models.BooleanField()),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField()),
                ('bioequivalente', models.BooleanField(default=False)),
                ('inventariado', models.BooleanField(default=False)),
                ('fecha_inventario', models.DateField()),
                ('controlado', models.BooleanField()),
                ('refrigerado', models.BooleanField()),
                ('composicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo_numero', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='barra',
            name='codigoproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Listado_productos'),
        ),
        migrations.AddField(
            model_name='barra',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Laboratorio'),
        ),
    ]
