# Generated by Django 2.0.4 on 2018-05-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180508_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barra2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barra', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Composicion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_una_dosis', models.PositiveSmallIntegerField()),
                ('dosis_por_envase', models.PositiveSmallIntegerField()),
                ('componente', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidora2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drogas2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigodroga', models.PositiveSmallIntegerField()),
                ('nombredroga', models.CharField(max_length=50)),
                ('refrigerado', models.BooleanField(default=False)),
                ('controlado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eliminados2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('codigo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('local', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.PositiveSmallIntegerField()),
                ('codigo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.PositiveSmallIntegerField()),
                ('stock_computador', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('fecha_inventario', models.DateTimeField()),
                ('diferencia_inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listado_productos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_barra', models.PositiveIntegerField()),
                ('preciocompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechacreacion', models.DateTimeField()),
                ('precioventa', models.PositiveSmallIntegerField()),
                ('conversion', models.PositiveSmallIntegerField()),
                ('factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido', models.PositiveSmallIntegerField()),
                ('stock', models.IntegerField()),
                ('fecha_ultima_compra', models.DateField()),
                ('faltas', models.BooleanField()),
                ('eliminado', models.BooleanField(default=False)),
                ('stock_minimo', models.PositiveSmallIntegerField()),
                ('stock_maximo', models.PositiveSmallIntegerField()),
                ('bioequivalente', models.BooleanField(default=False)),
                ('inventariado', models.BooleanField(default=False)),
                ('fecha_inventario', models.DateTimeField()),
                ('controlado', models.BooleanField(default=False)),
                ('refrigerado', models.BooleanField(default=False)),
                ('codigodroga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Drogas2')),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Composicion2')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Laboratorio2')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_numero', models.PositiveSmallIntegerField()),
                ('tipo_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='barra',
            name='codigoproducto',
        ),
        migrations.RemoveField(
            model_name='barra',
            name='laboratorio',
        ),
        migrations.DeleteModel(
            name='Composicion',
        ),
        migrations.DeleteModel(
            name='Eliminados',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.RemoveField(
            model_name='listado_productos',
            name='codigodroga',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='Barra',
        ),
        migrations.DeleteModel(
            name='Drogas',
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
        migrations.DeleteModel(
            name='Listado_productos',
        ),
        migrations.AddField(
            model_name='listado_productos2',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Tipo2'),
        ),
        migrations.AddField(
            model_name='listado_productos2',
            name='ultimo_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Proveedor2'),
        ),
        migrations.AddField(
            model_name='distribuidora2',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Listado_productos2'),
        ),
        migrations.AddField(
            model_name='distribuidora2',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Proveedor2'),
        ),
        migrations.AddField(
            model_name='composicion2',
            name='codigodroga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Drogas2'),
        ),
        migrations.AddField(
            model_name='barra2',
            name='codigoproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Listado_productos2'),
        ),
        migrations.AddField(
            model_name='barra2',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Laboratorio2'),
        ),
    ]
