# Generated by Django 2.0.4 on 2018-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=10)),
                ('digitoverificador', models.CharField(max_length=1)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('numerodecargas', models.IntegerField()),
            ],
        ),
    ]
