# Generated by Django 2.0.4 on 2018-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=10)),
                ('digitoverificador', models.CharField(max_length=1)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('numerodecargas', models.PositiveSmallIntegerField()),
                ('sueldobase', models.PositiveSmallIntegerField()),
                ('fecha_contrato', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
