# Generated by Django 2.0.4 on 2018-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_local',
            fields=[
                ('numero_local', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('representante', models.TextField()),
                ('telefono', models.IntegerField()),
                ('comuna', models.TextField()),
                ('ciudad', models.TextField()),
                ('nombre_farmacia', models.TextField()),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('fecha', models.DateTimeField(primary_key=True, serialize=False)),
                ('proceso', models.TextField()),
                ('codigo_antiguo', models.IntegerField()),
                ('codigo_nuevo', models.IntegerField()),
                ('nombre_antiguo', models.TextField()),
                ('nombre_nuevo', models.TextField()),
                ('precio_antiguo', models.IntegerField()),
                ('precio_nuevo', models.IntegerField()),
                ('local', models.IntegerField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.IntegerField()),
                ('password1', models.TextField()),
                ('password2', models.TextField()),
                ('password3', models.TextField()),
                ('fecha_password1', models.DateField()),
                ('fecha_password2', models.DateField()),
                ('fecha_password3', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_vendedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('vendedor', models.IntegerField()),
                ('venta', models.IntegerField()),
                ('sueldo', models.IntegerField()),
                ('cargas_familiares', models.IntegerField()),
                ('dias_trabajados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ultima_boleta',
            fields=[
                ('fecha', models.DateTimeField()),
                ('numero_boleta', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_mensuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('venta', models.IntegerField()),
                ('ganancia', models.IntegerField()),
                ('inventario', models.IntegerField()),
            ],
        ),
    ]
