# Generated by Django 2.0.4 on 2018-05-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_auto_20180520_1301'),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_local2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_local', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('nombre_farmacia', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('proceso', models.CharField(max_length=100)),
                ('codigo_antiguo', models.PositiveSmallIntegerField()),
                ('codigo_nuevo', models.PositiveSmallIntegerField()),
                ('nombre_antiguo', models.CharField(max_length=50)),
                ('nombre_nuevo', models.CharField(max_length=50)),
                ('precio_antiguo', models.PositiveSmallIntegerField()),
                ('precio_nuevo', models.PositiveSmallIntegerField()),
                ('local', models.PositiveSmallIntegerField()),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Password2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.PositiveSmallIntegerField()),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('password3', models.CharField(max_length=100)),
                ('fecha_password1', models.DateField()),
                ('fecha_password2', models.DateField()),
                ('fecha_password3', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_vendedores2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
                ('venta', models.PositiveSmallIntegerField()),
                ('sueldo', models.PositiveSmallIntegerField()),
                ('cargas_familiares', models.PositiveSmallIntegerField()),
                ('dias_trabajados', models.PositiveSmallIntegerField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.Vendedor2')),
            ],
        ),
        migrations.CreateModel(
            name='Ultima_boleta2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('numero_boleta', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_mensuales2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
                ('venta', models.PositiveSmallIntegerField()),
                ('ganancia', models.SmallIntegerField()),
                ('inventario', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Datos_local',
        ),
        migrations.DeleteModel(
            name='Observaciones',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='Resumen_vendedores',
        ),
        migrations.DeleteModel(
            name='Ultima_boleta',
        ),
        migrations.DeleteModel(
            name='Ventas_mensuales',
        ),
    ]
