# Generated by Django 2.0.4 on 2018-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cierres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechayhora_inicio', models.DateTimeField()),
                ('fechayhora_termino', models.DateTimeField()),
                ('vale_inicio', models.IntegerField()),
                ('vale_termino', models.IntegerField()),
                ('total_suma_ventas', models.IntegerField()),
                ('local', models.IntegerField()),
                ('total_dinero_en_caja', models.IntegerField()),
                ('total_gastos', models.IntegerField()),
                ('fondo_inicio', models.IntegerField()),
                ('tarjetas_credito', models.IntegerField()),
                ('tarjetas_debito', models.IntegerField()),
                ('dinerosextras1', models.IntegerField()),
                ('dinerosextras2', models.IntegerField()),
                ('dinerosextras3', models.IntegerField()),
                ('dinerosextras4', models.IntegerField()),
                ('bip_inicio', models.IntegerField()),
                ('bip_salida', models.IntegerField()),
                ('telefono_entrada', models.IntegerField()),
                ('telefono_salida', models.IntegerField()),
                ('celular_entrada', models.IntegerField()),
                ('celular_salida', models.IntegerField()),
                ('numero_cierre', models.IntegerField()),
                ('cajero', models.IntegerField()),
                ('suma_entradas', models.IntegerField()),
                ('suma_salidas', models.IntegerField()),
                ('diferencia_caja', models.IntegerField()),
                ('boleta_sii_inicial', models.IntegerField()),
                ('boleta_sii_final', models.IntegerField()),
                ('suma_boletas_sii', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cierre', models.IntegerField()),
                ('gasto', models.TextField()),
                ('monto', models.TextField()),
                ('numero_gasto', models.IntegerField()),
                ('fechayhora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('numero_gasto', models.IntegerField(primary_key=True, serialize=False)),
                ('gasto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_gasto', models.IntegerField()),
                ('gasto', models.IntegerField()),
            ],
        ),
    ]
