# Generated by Django 2.0.4 on 2018-05-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajeros2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cajero', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cierres2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechayhora_inicio', models.DateTimeField()),
                ('fechayhora_termino', models.DateTimeField()),
                ('vale_inicio', models.PositiveSmallIntegerField()),
                ('vale_termino', models.PositiveSmallIntegerField()),
                ('total_suma_ventas', models.PositiveSmallIntegerField()),
                ('local', models.PositiveSmallIntegerField()),
                ('total_dinero_en_caja', models.PositiveSmallIntegerField()),
                ('total_gastos', models.PositiveSmallIntegerField()),
                ('fondo_inicio', models.PositiveSmallIntegerField()),
                ('tarjetas_credito', models.PositiveSmallIntegerField()),
                ('tarjetas_debito', models.PositiveSmallIntegerField()),
                ('dinerosextras1', models.PositiveSmallIntegerField()),
                ('dinerosextras2', models.PositiveSmallIntegerField()),
                ('dinerosextras3', models.PositiveSmallIntegerField()),
                ('dinerosextras4', models.PositiveSmallIntegerField()),
                ('bip_inicio', models.PositiveSmallIntegerField()),
                ('bip_salida', models.PositiveSmallIntegerField()),
                ('telefono_entrada', models.PositiveSmallIntegerField()),
                ('telefono_salida', models.PositiveSmallIntegerField()),
                ('celular_entrada', models.PositiveSmallIntegerField()),
                ('celular_salida', models.PositiveSmallIntegerField()),
                ('numero_cierre', models.PositiveSmallIntegerField()),
                ('suma_entradas', models.PositiveSmallIntegerField()),
                ('suma_salidas', models.PositiveSmallIntegerField()),
                ('diferencia_caja', models.PositiveSmallIntegerField()),
                ('boleta_sii_inicial', models.PositiveSmallIntegerField()),
                ('boleta_sii_final', models.PositiveSmallIntegerField()),
                ('suma_boletas_sii', models.PositiveSmallIntegerField()),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gastos.Cajeros2')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_gastos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cierre', models.PositiveSmallIntegerField()),
                ('gasto', models.TextField()),
                ('monto', models.TextField()),
                ('fechayhora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gastos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gasto', models.PositiveSmallIntegerField()),
                ('gasto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_gastos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_gasto', models.PositiveSmallIntegerField()),
                ('gasto', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cierres',
        ),
        migrations.DeleteModel(
            name='Detalle_gastos',
        ),
        migrations.DeleteModel(
            name='Gastos',
        ),
        migrations.DeleteModel(
            name='Resumen_gastos',
        ),
        migrations.AddField(
            model_name='detalle_gastos2',
            name='numero_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gastos.Gastos2'),
        ),
    ]
