# Generated by Django 2.0.4 on 2018-05-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes2',
            fields=[
                ('rut', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('digitoverificador', models.CharField(default=0, max_length=1)),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('correo', models.EmailField(default='', max_length=254)),
                ('telefono', models.PositiveSmallIntegerField(default=0)),
                ('fechacreacion', models.DateField(auto_now_add=True)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_ventas2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale', models.IntegerField(default=0)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Clientes2')),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Registro_ventas',
        ),
    ]
